//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddVisualModelFromExistingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BusinessPartner
    {
        public long SR_ID_pk { get; set; }
        public string BP_PlaceholderID { get; set; }
        public string BP_ID { get; set; }
        public string BP_Name { get; set; }
        public string BP_UST_Nu { get; set; }
        public Nullable<int> BP_EmployeesNr { get; set; }
        public string BP_EMSPotential { get; set; }
        public string BP_EMPSPotential_Def { get; set; }
        public Nullable<int> BP_Rating { get; set; }
        public string BP_Rating_Def { get; set; }
        public string BP_BussinesBranche { get; set; }
        public string BP_BussinesBranche_Def { get; set; }
        public string BP_Language { get; set; }
        public string BP_Currency { get; set; }
        public string BP_Street { get; set; }
        public string BP_HouseNr { get; set; }
        public string BP_ZipCode { get; set; }
        public string BP_City { get; set; }
        public string BP_Country { get; set; }
        public string BP_Website { get; set; }
        public string BP_CurrentType { get; set; }
        public string is_Deleted { get; set; }
        public Nullable<System.DateTime> TimestampInregistrare { get; set; }
        public string PINDataEntry { get; set; }
    }
}
