//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddVisualModelFromExistingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ParticipantsLacon
    {
        public long SR_ID_pk { get; set; }
        public int PL_ID_PK { get; set; }
        public string PL_LaconCode { get; set; }
        public string PL_FullName { get; set; }
        public string PL_InformationIntegrity_Type { get; set; }
        public string is_Deleted { get; set; }
        public Nullable<System.DateTime> TimestampInregistrare { get; set; }
        public string PINDataEntry { get; set; }
    }
}
