//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddVisualModelFromExistingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CBP_Attributes
    {
        public string CBP_ASP_Code { get; set; }
        public string Att_Code { get; set; }
        public string Att_Def { get; set; }
        public string Att_Value { get; set; }
        public string is_Deleted { get; set; }
        public Nullable<System.DateTime> TimestampInregistrare { get; set; }
        public string PINDataEntry { get; set; }
    }
}
