//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddVisualModelFromExistingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesReport
    {
        public long SR_ID_pk { get; set; }
        public System.DateTime SR_DateTime { get; set; }
        public string SR_Author { get; set; }
        public string SR_Author_Name { get; set; }
        public string SR_ReasonOfVisit { get; set; }
        public string SR_Subject { get; set; }
        public string SR_LocationOrt { get; set; }
        public string SR_NextSteps { get; set; }
        public string SR_Fazit { get; set; }
        public Nullable<int> SR_Result { get; set; }
        public string SR_Result_Def { get; set; }
        public Nullable<int> SR_CurrentStatus { get; set; }
        public string SR_CurrentStatus_Def { get; set; }
        public string SR_InformationIntegrity_Type { get; set; }
        public string SR_CurrentType { get; set; }
        public string is_Deleted { get; set; }
        public Nullable<System.DateTime> TimestampInregistrare { get; set; }
        public string PINDataEntry { get; set; }
    }
}
