//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddVisualModelFromExistingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contacts_BusinessPartner
    {
        public long SR_ID_pk { get; set; }
        public int CBP_ID_PK { get; set; }
        public string CT_PlaceholderID { get; set; }
        public string CBP_ASP_Code { get; set; }
        public string CBP_FullName { get; set; }
        public string CBP_Position { get; set; }
        public string CBP_Departament { get; set; }
        public string CBP_Email { get; set; }
        public string CBP_Phone { get; set; }
        public string CBP_Mobile { get; set; }
        public string CBP_BuyerRole { get; set; }
        public string CBP_BuyerRole_Def { get; set; }
        public string CBP_CurrentType { get; set; }
        public string is_Deleted { get; set; }
        public Nullable<System.DateTime> TimestampInregistrare { get; set; }
        public string PINDataEntry { get; set; }
    }
}
