//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddVisualModelFromExistingDatabase_DashboardSP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbDashboard_SPEntities : DbContext
    {
        public dbDashboard_SPEntities()
            : base("name=dbDashboard_SPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblError> tblErrors { get; set; }
        public virtual DbSet<tblErrors_Def> tblErrors_Def { get; set; }
        public virtual DbSet<tblEmployee_Info> tblEmployee_Info { get; set; }
        public virtual DbSet<tblUploadDataVK_Purchase> tblUploadDataVK_Purchase { get; set; }
    }
}
