//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddVisualModelFromExistingDatabase_DashboardSP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblErrors_Def
    {
        public int Error_ID { get; set; }
        public string Error_Text { get; set; }
        public string Error_DepartmentType { get; set; }
        public Nullable<int> Error_SubdepartmentID { get; set; }
    }
}
