//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddVisualModelFromExistingDatabase_DashboardSP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUploadDataVK_Purchase
    {
        public int VK_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public Nullable<int> Count_Total { get; set; }
        public Nullable<int> Count_EK { get; set; }
        public Nullable<int> Count_FA { get; set; }
        public Nullable<int> Count_Green { get; set; }
        public Nullable<int> Count_Red { get; set; }
        public Nullable<int> Count_Yellow { get; set; }
        public Nullable<int> Count_Qty_Calculation { get; set; }
        public Nullable<int> Count_Lot_Production { get; set; }
        public string Handelspartner_Nr { get; set; }
        public string Handelspartner_Name { get; set; }
        public string Angebots_Nr { get; set; }
        public string Emp_Name { get; set; }
        public string FA_Nr { get; set; }
        public string FA_Description { get; set; }
        public Nullable<int> Sent_Emails { get; set; }
        public string Excel_Name { get; set; }
        public string Request_Type { get; set; }
        public string Excel_OldPrice { get; set; }
        public Nullable<int> Order_Qty { get; set; }
        public Nullable<decimal> Old_PriceEUR { get; set; }
        public Nullable<decimal> New_PriceEUR { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> TotalGain { get; set; }
        public string Comments { get; set; }
    }
}
