//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddVisualModelFromExistingDatabase_ItemSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartament
    {
        public string pkCOD_GRUPA { get; set; }
        public string DEN_GRUPA { get; set; }
    }
}
